# Generated by Django 4.1.4 on 2023-05-22 22:15

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('class_name', models.CharField(max_length=256)),
                ('function_name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('manager', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LimitationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=256)),
                ('limitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limitations', to='teacher_app.limitation')),
            ],
        ),
        migrations.CreateModel(
            name='LimitationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationLimitationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('limitation_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limitation_parameters', to='teacher_app.limitationparameter')),
            ],
        ),
    ]
