# Generated by Django 4.1.4 on 2023-05-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0002_limitation_alter_user_managers_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitationparameter',
            name='parameter',
        ),
        migrations.AddField(
            model_name='limitationparameter',
            name='parameter_in_code',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limitationparameter',
            name='parameter_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
