# Generated by Django 4.1.4 on 2023-05-22 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0003_remove_limitationparameter_parameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitationconfiguration',
            name='user',
        ),
        migrations.AddField(
            model_name='limitationconfiguration',
            name='limitation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config_limitations', to='teacher_app.limitation'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
                ('comment', models.CharField(max_length=1024)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='limitationconfiguration',
            name='configuration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='teacher_app.configuration'),
            preserve_default=False,
        ),
    ]
