# Generated by Django 4.1.4 on 2023-05-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0004_remove_limitationconfiguration_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
