# Generated by Django 4.1.4 on 2023-05-26 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0006_configurationlimitationparameter_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update time')),
                ('first_name', models.CharField(max_length=100, verbose_name='user name')),
                ('last_name', models.CharField(max_length=100, verbose_name='user surname')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='user patronymic')),
                ('group', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='filename',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
