# Generated by Django 4.1.4 on 2023-06-02 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0007_student_configuration_filename_configuration_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, null=True, upload_to='')),
                ('time_started', models.DateTimeField()),
                ('time_ended', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='teacher_app.student')),
            ],
        ),
    ]
