# Generated by Django 4.1.4 on 2023-06-02 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0008_configurationstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationstatistics',
            name='configuration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stats_configurations', to='teacher_app.configuration'),
            preserve_default=False,
        ),
    ]
