# Generated by Django 4.1.4 on 2023-06-02 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0009_configurationstatistics_configuration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': 'Конфигурация', 'verbose_name_plural': 'Конфигурации'},
        ),
        migrations.AlterModelOptions(
            name='configurationlimitationparameter',
            options={'verbose_name': 'Параметр ограничения для конфигурации', 'verbose_name_plural': 'Параметры ограничения для конфигурации'},
        ),
        migrations.AlterModelOptions(
            name='configurationstatistics',
            options={'verbose_name': 'Статистика конфигурации', 'verbose_name_plural': 'Статистика конфигурации'},
        ),
        migrations.AlterModelOptions(
            name='limitation',
            options={'verbose_name': 'Ограничение', 'verbose_name_plural': 'Ограничения'},
        ),
        migrations.AlterModelOptions(
            name='limitationparameter',
            options={'verbose_name': 'Параметр ограничения', 'verbose_name_plural': 'Параметры ограничения'},
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='class_name',
        ),
        migrations.AddField(
            model_name='limitation',
            name='type',
            field=models.CharField(choices=[('Классы', 'Classes'), ('Списки', 'Lists'), ('Словари', 'Dicts')], default='classes', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configurationstatistics',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_configurations', to='teacher_app.configuration', verbose_name='Конфигурация'),
        ),
        migrations.AlterField(
            model_name='configurationstatistics',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='', verbose_name='Файл с результатами проверки'),
        ),
        migrations.AlterField(
            model_name='configurationstatistics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='teacher_app.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='configurationstatistics',
            name='time_ended',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='configurationstatistics',
            name='time_started',
            field=models.DateTimeField(verbose_name='Время начала'),
        ),
    ]
