# Generated by Django 4.1.4 on 2023-06-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0010_alter_configuration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitationparameter',
            name='check_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='type',
            field=models.CharField(choices=[('Классы', 'Classes'), ('Списки', 'Lists'), ('Словари', 'Dicts')], max_length=256, verbose_name='Объекты'),
        ),
    ]
