# Generated by Django 4.1.4 on 2023-06-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0011_limitationparameter_check_type_alter_limitation_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitationparameter',
            name='check_type',
        ),
        migrations.AddField(
            model_name='configurationlimitationparameter',
            name='check_type',
            field=models.IntegerField(default=0),
        ),
    ]
