repos:
    -   repo: https://github.com/python/black
        rev: '22.3.0'
        hooks:
            -   id: black
                exclude: (.*/migrations)|(.*/__init__.py)
                language_version: python3

    -   repo: https://gitlab.com/pycqa/flake8
        rev: '3.8.1'
        hooks:
            -   id: flake8
                args: [ "--max-line-length", "120", "--ignore", "E203,W503" ]
                exclude: (.*/migrations)|(.*/__init__.py)|(.*/settings_test.py)

    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.4.0
        hooks:
            -   id: trailing-whitespace
            -   id: end-of-file-fixer
            -   id: check-case-conflict
            -   id: check-merge-conflict
            -   id: check-yaml
            -   id: check-json
            -   id: check-docstring-first
            -   id: debug-statements
            -   id: mixed-line-ending
