version: '3'

services:
    db:
        image: postgres:11.1-alpine
        ports:
            - 127.0.0.1:5432:5432
        command: postgres -c log_statement=all
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_DB: ${POSTGRES_DATABASE_NAME:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

    redis:
        image: redis:6-alpine
        ports:
            - 127.0.0.1:6379:6379
        command: redis-server --appendonly yes
        volumes:
            - redis:/data

#    pgadmin:
#        image: dpage/pgadmin4
#        environment:
#            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
#            PGADMIN_DEFAULT_PASSWORD: "admin"
#        ports:
#            - 127.0.0.1:5050:80
#        depends_on:
#            - db

volumes:
    postgres:
    redis:
